/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package own_camping;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import konfig.koneksi;

/**
 *
 * @author Mozict
 */
public class Datapenyewa extends javax.swing.JInternalFrame {

    /**
     * Creates new form Datapenyewa
     */
    String Id_penyewa;
    public Datapenyewa() {
        initComponents();
        datatabel();
        tanggalSaatini();
        nonaktif();
    }
    
    //menonaktifkan tombol button
    public void nonaktif(){
        bt_hapus.setEnabled(false);
        bt_Edit.setEnabled(false);
    }
    public void kosongkan(){
        txtAlamat.setText(null);
        txtnama.setText(null);
        txtnotlp.setText(null);
        txtno_KTP.setText(null);
        tanggalSaatini();
    }
    //update tanggal saat ini
    public void tanggalSaatini(){
        Date date=new Date();
        jctgl.setDate(date);
    }
     //tampil tabel penyewaan 
    public void datatabel(){
        DefaultTableModel tbl=new DefaultTableModel();
        tbl.addColumn("ID PNY");
        tbl.addColumn("PENYEWA");
        tbl.addColumn("TGL");
        tbl.addColumn("No KTP/SIM/KTM");
        tbl.addColumn("NO HP");
        tbl.addColumn("ALAMAT");
        tabel_penyewaan.setModel(tbl);
        try {
            Statement statment=(Statement)koneksi.GetconConnection().createStatement();
            ResultSet res=statment.executeQuery("select * from penyewa");
            while(res.next()){
                tbl.addRow(new Object[]{
                    res.getString("id_penyewa"),
                    res.getString("nm_penyewa"),
                    res.getString("tgl"),
                    res.getString("no_ktp"),
                    res.getString("notlp"),
                    res.getString("alamat")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tabel Bermasalah");
            e.printStackTrace();
        }
    }
    public void tambahData(){
        String tampilan ="Y-MM-dd";
        SimpleDateFormat format=new SimpleDateFormat(tampilan);
        String tanggal=String.valueOf(format.format(this.jctgl.getDate()));
        String nama=txtnama.getText();
        String notlp=txtnotlp.getText();
        String alamat=txtAlamat.getText();
        String no_ktp=txtno_KTP.getText();
        if(txtnama.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Data Penyewa Eror");
        }else if(txtnotlp.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Data Nomer Telpon Eror");
        }else if (txtAlamat.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Data Alamat Eror");
        }else{
            try {
                Statement statment=(Statement)koneksi.GetconConnection().createStatement();
                statment.execute("INSERT into penyewa (nm_penyewa,tgl,no_ktp,notlp,alamat)values ('"+nama+"','"+tanggal+"','"+no_ktp+"','"+notlp+"','"+alamat+"')");
                kosongkan();
                JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Data Gagal Disimpan");
            }
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jctgl = new com.toedter.calendar.JDateChooser();
        txtnama = new javax.swing.JTextField();
        txtnotlp = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_penyewaan = new javax.swing.JTable();
        bt_tambah = new javax.swing.JButton();
        bt_Edit = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        bt_keluar = new javax.swing.JButton();
        bt_cari = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtno_KTP = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Penyewa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel2.setText("Nama Penyewa");

        jLabel3.setText("Tanggal");

        jLabel4.setText("No Telpon");

        jLabel5.setText("Alamat");

        txtnotlp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnotlpKeyTyped(evt);
            }
        });

        tabel_penyewaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_penyewaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_penyewaanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_penyewaan);

        bt_tambah.setText("Tambah");
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });

        bt_Edit.setText("Edit");
        bt_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EditActionPerformed(evt);
            }
        });

        bt_hapus.setText("Hapus");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        bt_keluar.setText("Keluar");
        bt_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_keluarActionPerformed(evt);
            }
        });

        bt_cari.setText("Cari");
        bt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cariActionPerformed(evt);
            }
        });

        jLabel6.setText("No KTP/SIM/KTM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jctgl, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAlamat)
                                .addComponent(txtnama)
                                .addComponent(txtnotlp, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bt_cari)))
                            .addComponent(txtno_KTP, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_tambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(bt_Edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_hapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_keluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_tambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jctgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_Edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_hapus)
                    .addComponent(jLabel6)
                    .addComponent(txtno_KTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_keluar)
                    .addComponent(jLabel4)
                    .addComponent(txtnotlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bt_keluarActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        // TODO add your handling code here:
        tambahData();
        datatabel();        
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void tabel_penyewaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_penyewaanMouseClicked
        // TODO add your handling code here:
        int baris =tabel_penyewaan.rowAtPoint(evt.getPoint());
        Id_penyewa=tabel_penyewaan.getValueAt(baris, 0).toString();
        String nama=tabel_penyewaan.getValueAt(baris, 1).toString();
        txtnama.setText(nama);
        try {
            String tgl=tabel_penyewaan.getValueAt(baris, 2).toString();
            java.util.Date date= new SimpleDateFormat("yyyy-MM-dd").parse(tgl);
            jctgl.setDate(date);
        } catch (Exception e) {
        }
         String no_ktp=tabel_penyewaan.getValueAt(baris, 3).toString();
        txtno_KTP.setText(no_ktp);
        String notlp=tabel_penyewaan.getValueAt(baris, 4).toString();
        txtnotlp.setText(notlp);
        String Alamat=tabel_penyewaan.getValueAt(baris, 5).toString();
        txtAlamat.setText(Alamat);
        bt_Edit.setEnabled(true);
        bt_hapus.setEnabled(true);
        bt_tambah.setEnabled(false);
        
    }//GEN-LAST:event_tabel_penyewaanMouseClicked

    private void bt_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EditActionPerformed
        // TODO add your handling code here:
        String tampilan ="Y-MM-dd";
        SimpleDateFormat format=new SimpleDateFormat(tampilan);
        String tanggal=String.valueOf(format.format(this.jctgl.getDate()));
        String nama=txtnama.getText();
        String notlp=txtnotlp.getText();
        String alamat=txtAlamat.getText();
        String no_ktp=txtno_KTP.getText();
        
        try {
            Statement statement=(Statement)koneksi.GetconConnection().createStatement();
            statement.executeUpdate("UPDATE penyewa SET nm_penyewa='"+nama+"',tgl='"+tanggal+"',no_ktp='"+no_ktp+"',notlp='"+notlp+"',alamat='"+alamat+"'where id_penyewa='"+Id_penyewa+"' ");
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Update");
            kosongkan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Di Update");
            e.printStackTrace();
        }
        datatabel();
        nonaktif();
        bt_tambah.setEnabled(true);
    }//GEN-LAST:event_bt_EditActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
        try {
            Statement statement=(Statement)koneksi.GetconConnection().createStatement();
            statement.execute("DELETE from penyewa Where id_penyewa='"+Id_penyewa+"'");
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            kosongkan();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Data Gagal Dihapus");
        }
        datatabel();
        bt_tambah.setEnabled(true);
        nonaktif();
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void txtnotlpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnotlpKeyTyped
        // TODO add your handling code here:
         char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
        getToolkit().beep();
        evt.consume();
            }
    }//GEN-LAST:event_txtnotlpKeyTyped

    private void bt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_cariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Edit;
    private javax.swing.JButton bt_cari;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_keluar;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jctgl;
    private javax.swing.JTable tabel_penyewaan;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtno_KTP;
    private javax.swing.JTextField txtnotlp;
    // End of variables declaration//GEN-END:variables
}
