/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package own_camping;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import konfig.koneksi;

/**
 *
 * @author Fatma Wati
 */
public class Dataperalatan extends javax.swing.JInternalFrame {

    /**
     * Creates new form Dataperalatan
     */
    public Dataperalatan() {
        initComponents();
        datatabel();
        nonaktif();
    }
    //non aktifkan tombol
    public void nonaktif(){
        bt_hapus.setEnabled(false);
        btedit.setEnabled(false);
    }
    public void kosongkan(){
        txtJml.setText(null);
        txthargaBeli.setText(null);
        txthargaSewa.setText(null);
        txtidPeralatan.setText(null);
        txtnmPeralatan.setText(null);
    }
    //tampil tabel peralatan 
    public void datatabel(){
        DefaultTableModel tbl=new DefaultTableModel();
        tbl.addColumn("ID PRLT");
        tbl.addColumn("PERALATAN");
        tbl.addColumn("JML");
        tbl.addColumn("BELI");
        tbl.addColumn("SEWA");
        tabel_peralatan.setModel(tbl);
        try {
            Statement statment=(Statement)koneksi.GetconConnection().createStatement();
            ResultSet res=statment.executeQuery("select * from peralatan");
            while(res.next()){
                tbl.addRow(new Object[]{
                    res.getString("id_peralatan"),
                    res.getString("nm_peralatan"),
                    res.getString("jml"),
                    res.getString("hrg_beli"),
                    res.getString("hrg_sewa")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tabel Bermasalah");
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtidPeralatan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnmPeralatan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txthargaBeli = new javax.swing.JTextField();
        bt_tambah = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_peralatan = new javax.swing.JTable();
        btKeluar = new javax.swing.JButton();
        bt_cari = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txthargaSewa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtJml = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Kode barang");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Data Barang Sewa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Nama Barang");

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Harga Beli");

        txthargaBeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthargaBeliKeyTyped(evt);
            }
        });

        bt_tambah.setBackground(new java.awt.Color(153, 153, 153));
        bt_tambah.setForeground(new java.awt.Color(255, 255, 0));
        bt_tambah.setText("Tambah");
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });

        btedit.setBackground(new java.awt.Color(153, 153, 153));
        btedit.setForeground(new java.awt.Color(255, 255, 0));
        btedit.setText("Edit");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });

        bt_hapus.setBackground(new java.awt.Color(153, 153, 153));
        bt_hapus.setForeground(new java.awt.Color(255, 255, 0));
        bt_hapus.setText("Hapus");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        tabel_peralatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_peralatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_peralatanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_peralatan);

        btKeluar.setBackground(new java.awt.Color(153, 153, 153));
        btKeluar.setForeground(new java.awt.Color(255, 255, 0));
        btKeluar.setText("Keluar");
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });

        bt_cari.setBackground(new java.awt.Color(153, 153, 153));
        bt_cari.setForeground(new java.awt.Color(255, 255, 0));
        bt_cari.setText("Cari");
        bt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cariActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Harga Sewa");

        txthargaSewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthargaSewaKeyTyped(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Jumlah");

        txtJml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJmlKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtidPeralatan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnmPeralatan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(117, 117, 117)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addComponent(txthargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txthargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_cari)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtJml, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_tambah)
                                .addGap(18, 18, 18)
                                .addComponent(btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_hapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidPeralatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cari)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txthargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnmPeralatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txtJml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_tambah)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btedit)
                        .addComponent(bt_hapus)
                        .addComponent(btKeluar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btKeluarActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        // TODO add your handling code here:
        String idPeralatan=txtidPeralatan.getText();
        String nmPeralatan=txtnmPeralatan.getText();
        String jml=txtJml.getText();
        String hargaBeli=txthargaBeli.getText();
        String hargaSewa=txthargaSewa.getText();
        if(txtidPeralatan.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Data ID Eror");
        }else if(txtnmPeralatan.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Data Nama Eror");
        }else if(txthargaBeli.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Data Harga Beli Eror");
        }else if(txthargaSewa.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Data Harga Sewa Eror");
        }else if(txtJml.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Data Jumlah Eror");
        }else {
                try {
                    Statement statement=(Statement)koneksi.GetconConnection().createStatement();
                    statement.executeUpdate("insert into peralatan values ('"+idPeralatan+"','"+nmPeralatan+"','"+jml+"','"+hargaBeli+"','"+hargaSewa+"')");
                    statement.close();
                    JOptionPane.showMessageDialog(rootPane, "Data Berhasil Disimpan");
                    kosongkan();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Data Gagal Disimpan");
                    e.printStackTrace();
                }
                datatabel();
        }
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void tabel_peralatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_peralatanMouseClicked
        // TODO add your handling code here:
        int baris=tabel_peralatan.rowAtPoint(evt.getPoint());
        String idPeralatan=tabel_peralatan.getValueAt(baris, 0).toString();
        txtidPeralatan.setText(idPeralatan);
        String nmPeralatan=tabel_peralatan.getValueAt(baris, 1).toString();
        txtnmPeralatan.setText(nmPeralatan);
        String jml=tabel_peralatan.getValueAt(baris, 2).toString();
        txtJml.setText(jml);
        String hargaBeli=tabel_peralatan.getValueAt(baris, 3).toString();
        txthargaBeli.setText(hargaBeli);
        String hargaSewa=tabel_peralatan.getValueAt(baris, 4).toString();
        txthargaSewa.setText(hargaSewa);
        bt_hapus.setEnabled(true);
        btedit.setEnabled(true);
        bt_tambah.setEnabled(false);
    }//GEN-LAST:event_tabel_peralatanMouseClicked

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        // TODO add your handling code here:
        String idPeralatan=txtidPeralatan.getText();
        String nmPeralatan=txtnmPeralatan.getText();
        String jml=txtJml.getText();
        String hargaBeli=txthargaBeli.getText();
        String hargaSewa=txthargaSewa.getText();
        
        try {
            Statement statement=(Statement)koneksi.GetconConnection().createStatement();
            statement.execute("UPDATE peralatan SET nm_peralatan='"+nmPeralatan+"',jml='"+jml+"',hrg_beli='"+hargaBeli+"',hrg_sewa='"+hargaSewa+"' where id_peralatan='"+idPeralatan+"'");
            statement.close();
            nonaktif();
            kosongkan();
            bt_tambah.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Update");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Di Update");
            e.printStackTrace();
        }
        datatabel();
    }//GEN-LAST:event_bteditActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
         String idPeralatan=txtidPeralatan.getText();
        try {
            Statement statment=(Statement)koneksi.GetconConnection().createStatement();
            statment.execute("DELETE from peralatan where id_peralatan='"+idPeralatan+"'");
            statment.close();
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            nonaktif();
            kosongkan();
            bt_tambah.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Dihapus");
            e.printStackTrace();
        }
        datatabel();
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void txthargaBeliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargaBeliKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
        getToolkit().beep();
        evt.consume();
            }
    }//GEN-LAST:event_txthargaBeliKeyTyped

    private void txthargaSewaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargaSewaKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
        getToolkit().beep();
        evt.consume();
            }
    }//GEN-LAST:event_txthargaSewaKeyTyped

    private void txtJmlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJmlKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
        getToolkit().beep();
        evt.consume();
            }
    }//GEN-LAST:event_txtJmlKeyTyped

    private void bt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_cariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton bt_cari;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JButton btedit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tabel_peralatan;
    private javax.swing.JTextField txtJml;
    private javax.swing.JTextField txthargaBeli;
    private javax.swing.JTextField txthargaSewa;
    private javax.swing.JTextField txtidPeralatan;
    private javax.swing.JTextField txtnmPeralatan;
    // End of variables declaration//GEN-END:variables
}
