/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package own_camping;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import konfig.koneksi;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Mozict
 */
public class lapPendapatanDenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form lapPendapatanDenda
     */
    public lapPendapatanDenda() {
        initComponents();
    }
     public void caridata(){
        String tampilan="Y-MM-dd";
        SimpleDateFormat format=new SimpleDateFormat(tampilan);
        String tgl1=String.valueOf(format.format(this.jctgl1.getDate()));
        String tampilan2="Y-MM-dd";
        SimpleDateFormat format2=new SimpleDateFormat(tampilan2);
        String tgl2=String.valueOf(format.format(this.jctgl2.getDate())); 
        
        try {
            Statement statment=koneksi.GetconConnection().createStatement();
            ResultSet rs=statment.executeQuery("SELECT *FROM denda join peralatan on denda.id_peralatan = peralatan.id_peralatan join penyewa on denda.id_penyewa = penyewa.id_penyewa where DATE_FORMAT(denda.tgl_kembalii,'%Y-%m-%d')>='"+tgl1+"'and DATE_FORMAT(denda.tgl_kembalii,'%Y-%m-%d')<='"+tgl2+"'");
            DefaultTableModel tbl=new DefaultTableModel();
            tbl.addColumn("ID Denda");
            tbl.addColumn("ID Kembali");
            tbl.addColumn("Penyewa");
            tbl.addColumn("Peralatan");
            tbl.addColumn("TGL Kembali");
            tbl.addColumn("Denda");
            tbl.addColumn("Status");
            tblPendapatanSewa.setModel(tbl);
            
            while(rs.next()){
                tbl.addRow(new Object[]{
                    rs.getString("id_denda"),
                    rs.getString("id_transaksi_pengembalian"),
                    rs.getString("nm_peralatan"),
                    rs.getString("nm_peralatan"),
                    rs.getString("tgl_kembalii"),
                    rs.getString("denda"),
                    rs.getString("status")
                });
                tblPendapatanSewa.setModel(tbl);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPendapatanSewa = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jctgl1 = new com.toedter.calendar.JDateChooser();
        jctgl2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        tblPendapatanSewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPendapatanSewa);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Sampai");

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(412, 412, 412)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jctgl1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jctgl2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(424, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jctgl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jctgl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LAPORAN PENDAAPATAN DENDA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        caridata();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String tampilan="Y-MM-dd";
        SimpleDateFormat format=new SimpleDateFormat(tampilan);
        String tgl1=String.valueOf(format.format(this.jctgl1.getDate()));
        String tampilan2="Y-MM-dd";
        SimpleDateFormat format2=new SimpleDateFormat(tampilan2);
        String tgl2=String.valueOf(format.format(this.jctgl2.getDate()));
        
        JasperReport jasRep;
        JasperPrint jasPrint;
        Map<String, Object> Transaksi=new HashMap<String, Object>();
        JasperDesign jasDes;
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/owncamping","root","");
            String report="./src/laporan/LapDenda.jrxml";
            jasDes = JRXmlLoader.load(report);
            Transaksi.put("tgl1",tgl1);
            Transaksi.put("tgl2",tgl2);
            jasRep=JasperCompileManager.compileReport(jasDes);
            jasPrint=JasperFillManager.fillReport(jasRep, Transaksi, koneksi);
            JasperViewer.viewReport(jasPrint,false);
            
        } catch (Exception e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        String tampilan="Y-MM-dd";
        SimpleDateFormat format=new SimpleDateFormat(tampilan);
        String tgl1=String.valueOf(format.format(this.jctgl1.getDate()));
        String tampilan2="Y-MM-dd";
        SimpleDateFormat format2=new SimpleDateFormat(tampilan2);
        String tgl2=String.valueOf(format.format(this.jctgl2.getDate())); 
        
        JasperReport jasRep;
        JasperPrint jasPrint;
        Map<String, Object> Transaksi=new HashMap<String, Object>();
        JasperDesign jasDes;
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/owncamping","root","");
            String report="./src/laporan/lapSewa.jrxml";
            jasDes = JRXmlLoader.load(report);
            Transaksi.put("tgl1",tgl1);
            Transaksi.put("tgl2",tgl2);
            jasRep=JasperCompileManager.compileReport(jasDes);
            jasPrint=JasperFillManager.fillReport(jasRep, Transaksi, koneksi);
            JasperViewer.viewReport(jasPrint,false);
            
        } catch (Exception e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jctgl1;
    private com.toedter.calendar.JDateChooser jctgl2;
    private javax.swing.JTable tblPendapatanSewa;
    // End of variables declaration//GEN-END:variables
}
