/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package own_camping;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import konfig.koneksi;

/**
 *
 * @author Mozict
 */
public class SourcePeralatan extends javax.swing.JDialog {

    /**
     * Creates new form SourcePeralatan
     */
    public Transaksi fAB = null;
    public SourcePeralatan() {
        initComponents();
        datatabel();
        this.setLocationRelativeTo(null);
    }
    
    //tampil tabel
   public void datatabel(){
        DefaultTableModel tbl=new DefaultTableModel();
        tbl.addColumn("ID PRLT");
        tbl.addColumn("PERALATAN");
        tbl.addColumn("JML");
        tbl.addColumn("BELI");
        tbl.addColumn("SEWA");
        tabel_peralatan.setModel(tbl);
        try {
            Statement statment=(Statement)koneksi.GetconConnection().createStatement();
            ResultSet res=statment.executeQuery("select * from peralatan");
            while(res.next()){
                tbl.addRow(new Object[]{
                    res.getString("id_peralatan"),
                    res.getString("nm_peralatan"),
                    res.getString("jml"),
                    res.getString("hrg_beli"),
                    res.getString("hrg_sewa")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tabel Bermasalah");
            e.printStackTrace();
        }
    
    }
   
    public void cari(){
        try {
            Statement statment=koneksi.GetconConnection().createStatement();
            ResultSet rs=statment.executeQuery("Select * from peralatan where id_peralatan='"+txtcari.getText()+"' or nm_peralatan='"+txtcari.getText()+"'");
            
            
            DefaultTableModel tbl=new DefaultTableModel();
            tbl.addColumn("ID PRLT");
            tbl.addColumn("PERALATAN");
            tbl.addColumn("JML");
            tbl.addColumn("BELI");
            tbl.addColumn("SEWA");
            tabel_peralatan.setModel(tbl);
            while(rs.next()){
                tbl.addRow(new Object[]{
                    rs.getString("id_peralatan"),
                    rs.getString("nm_peralatan"),
                    rs.getString("jml"),
                    rs.getString("hrg_beli"),
                    rs.getString("hrg_sewa")
                });
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        txtcari = new javax.swing.JTextField();
        btCek = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_peralatan = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 255));

        jDesktopPane1.setBackground(new java.awt.Color(51, 0, 255));

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });

        btCek.setText("Cek");
        btCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCekActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setText("Nama Peralatan");

        jLabel2.setBackground(new java.awt.Color(0, 51, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CEK DATA PINJAMAN PERALATAN");

        tabel_peralatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_peralatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_peralatanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabel_peralatanMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_peralatan);

        jButton1.setText("Refrese");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(txtcari, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btCek, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(btCek)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCek)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCekActionPerformed
        // TODO add your handling code here
        cari();
        
    }//GEN-LAST:event_btCekActionPerformed

    private void tabel_peralatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_peralatanMouseClicked
        // TODO add your handling code here:
        int baris=tabel_peralatan.getSelectedRow();
        fAB.id_peralatan=tabel_peralatan.getValueAt(baris, 0).toString();
        fAB.nm_peralatan=tabel_peralatan.getValueAt(baris, 1).toString();
        fAB.itemTerpilih();
        this.dispose();
        
    }//GEN-LAST:event_tabel_peralatanMouseClicked

    private void tabel_peralatanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_peralatanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_peralatanMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        datatabel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            cari();
        }
    }//GEN-LAST:event_txtcariKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCek;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_peralatan;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
